version: "3.7"

services:
  datasource-postgres-green:
    image: circleci/postgres:11.6-postgis
    container_name: analytics-datasource-green-postgres
    environment:
      - POSTGRES_USER=pass_culture
      - POSTGRES_PASSWORD=passq
      - POSTGRES_DB=pass_culture
      - DATABASE_URL=postgresql://pass_culture:passq@datasource-postgres-green:5432/pass_culture
    ports:
      - 5437:5432
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_min_duration_statement=0 -c log_statement=all -c log_duration=on

  postgres-metabase:
    image: postgres:10.10-alpine
    container_name: pcm-postgres-metabase
    environment:
      - POSTGRES_DB=pass_culture
      - POSTGRES_USER=metabase
      - POSTGRES_PASSWORD=metabase
    volumes:
      - metabase_data:/var/lib/postgresql/data/
    ports:
      - 5436:5432
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_min_duration_statement=0 -c log_statement=all -c log_duration=on

  metabase-app:
    container_name: pcm-metabase-app
    image: metabase/metabase:v0.34.1
    ports:
      - 3002:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: pass_culture
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: postgres-metabase
    depends_on:
      - postgres-metabase
    links:
      - postgres-metabase

volumes:
  metabase_data:
