version: "3.7"

services:
  datasource-application:
    image: python:3.6-stretch
    container_name: analytics-datasource-application
    volumes:
      - .:/opt/data-analytics
    command: >
      bash -c "pip install -r /opt/data-analytics/requirements.txt;
               python /opt/data-analytics/app.py;
               "
    ports:
      - 5000:5000
    env_file:
      - env_file
    depends_on:
      - datasource-postgres-blue

  install-models:
    image: python:3.6-stretch
    container_name: pcm-install-models
    volumes:
      - .:/opt/enriched_data
    command: >
      bash -c "cd /opt;
               git clone https://github.com/betagouv/pass-culture-api.git;
               cd pass-culture-api;
               pip install -r requirements.txt;
               python -m nltk.downloader punkt stopwords;
               python install_database_extensions.py
               PYTHONPATH=. alembic upgrade head
               "
    env_file:
      - env_file
    depends_on:
      - datasource-postgres-blue

  datasource-postgres-blue:
    image: circleci/postgres:11.6-postgis
    container_name: analytics-datasource-blue-postgres
    env_file:
      - env_file
    ports:
      - 5435:5432
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_min_duration_statement=0 -c log_statement=all -c log_duration=on

  datasource-postgres-green:
    image: circleci/postgres:11.6-postgis
    container_name: analytics-datasource-green-postgres
    environment:
      - POSTGRES_USER=pass_culture
      - POSTGRES_PASSWORD=passq
      - POSTGRES_DB=pass_culture
      - DATABASE_URL=postgresql://pass_culture:passq@localhost:5437/pass_culture
    ports:
      - 5437:5432
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_min_duration_statement=0 -c log_statement=all -c log_duration=on

  postgres-metabase:
    image: postgres:10.10-alpine
    container_name: pcm-postgres-metabase
    environment:
      - POSTGRES_DB=pass_culture
      - POSTGRES_USER=metabase
      - POSTGRES_PASSWORD=metabase
    ports:
      - 5436:5432
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_min_duration_statement=0 -c log_statement=all -c log_duration=on

  metabase-app:
    container_name: pcm-metabase-app
    image: metabase/metabase
    ports:
      - 3002:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: pass_culture
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: postgres-metabase
    depends_on:
      - postgres-metabase
    links:
      - postgres-metabase
